/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#67655f",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "primary-container": "#8b5a2b",
        "on-primary-container": "#ffddc2",
        "secondary-container": "#5c4214",
        "on-primary": "#4c2700",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#432c01",
        "surface": "var(--color-surface, #131313)",
        "secondary": "#e7c187",
        "on-tertiary-container": "#e7e3db",
        "on-tertiary": "#32302b",
        "outline-variant": "#51443a",
        "inverse-on-surface": "#313030",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#1d1c17",
        "surface-bright": "#3a3939",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "surface-tint": "var(--color-primary, #D4AF77)",
        "surface-dim": "var(--color-surface, #131313)",
        "on-secondary-container": "#d4af77",
        "outline": "#9e8e82",
        "on-primary-fixed-variant": "#683d0f",
        "tertiary-fixed-dim": "#cac6be",
        "secondary-fixed": "#ffdeae",
        "on-surface-variant": "#d5c3b6",
        "secondary-fixed-dim": "#e7c187",
        "primary-fixed-dim": "var(--color-primary, #D4AF77)",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed": "#2e1500",
        "surface-variant": "#353534",
        "tertiary-fixed": "#e7e2da",
        "on-secondary-fixed-variant": "#5c4214",
        "tertiary": "#cac6be",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffdcc1",
        "on-tertiary-fixed-variant": "#494741",
        "on-secondary-fixed": "#281900",
        "inverse-primary": "#835425",
        "on-error": "#690005",
        "background": "var(--color-surface, #131313)",
        "primary": "var(--color-primary, #D4AF77)",
        "error-container": "#93000a",
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
